name: Application Testing and Deployment

on:

  push:

    branches:

      - main

env:

  TALKING_API_KEY: ${{secrets.SECRET_KEY}}

  TALKING_USERNAME: ${{secrets.SECRET_KEY}}

  TALKING_SHORT_CODE: ${{secrets.SECRET_KEY}}

jobs:

  Testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out the repo

        uses: actions/checkout@v2

      - name: setting up python environment

        uses: actions/setup-python@v2

      - name: setting up poetry

        uses: abatilo/actions-poetry@v2

      - name : Installing Dependencies

        run: poetry install --no-root

      - name: Testing the Application

        run: poetry run flask test

      - name: Linting the Source code

        run: |

          poetry add flake8

          poetry run flake8 . --count --select E9,F63,F7,F82 --exclude __pycache__ --show-source --statistics

          poetry run flake8 . --count --max-complexity=10 --max-line-length=100 --ignore C901,E121,E122,E221,E126,E231,E123,E731,F841,W503,W293,W504 --exclude __pycache__,migrations,env --show-source --statistics

  Deploy:

    needs: Testing

    runs-on: self-hosted

    steps:

      - name: Checking out the repo
        uses: actions/checkout@v2

      - name: Deploy updates

        run: |

          sudo chmod +x configure_nginx.sh Setup.py

          ./Setup.py