name: Application Testing and Deployment

on:

  push:

    branches:

      - main

jobs:

  Testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checking out the repo

        uses: actions/checkout@v2

      - name: setting up python environment

        uses: actions/setup-python@v2

      - name : Installing Dependencies

        run: |

          python - m pip install --upgrade pip

          pip install -r requirements.txt

      - name: Testing the Application

        run: flask test

      - name: Linting the Source code

        run: |

          pip install flake8

          flake8 . --count --select E9,F63,F7,F82 --exclude __pycache__ --show-source --statistics

          flake8 . --count --max-complexity=10 --max-line-length=100 --ignore C901,E121,E122,E221,E126,E231,E123,F841,W503,W293,W504 --exclude __pycache__,migrations,env --show-source --statistics

  Deploy:

    needs: Testing

    runs-on: self-hosted

    steps:

      - name: Checking out the repo
        uses: actions/checkout@v2

      - name: Deploy updates

        run: |

          sudo chmod +x configure_nginx.sh Setup.sh

          ./Setup.py